[package]
name = "launchd-register"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.69.0"
cc = "1.0.79"
clap = { version = "4.1.13", features = ["derive"] }
